version: 2.1
parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.medium
    steps:
      - run:
          name: "BUILD"
          environment:
            ARCH: aarch64
          command: |
            git clone https://github.com/termux-user-repository/tur --depth 1
            cd tur
            ./setup-environment.sh
            ./common-files/build-termux-docker.sh login ./scripts/setup-termux.sh
            docker system prune -a -f
            sudo chown -R 1000:1000 $(pwd)
            ./common-files/build-termux-docker.sh login ./build-package.sh -I tur-on-device/blender

workflows:
  build:
    jobs:
      - build
